"""
THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

Copyright 2016 Trusted Objects

@brief       Secure Element Python utils: constants
@author      Trusted-Objects
"""

TO_OK = 0
TO_ERROR = 0xF000

INVALID_PARAMETERS = 500

IV_SIZE = 16
HMAC_SIZE = 32
HMAC_KEY_SIZE = 16
CMAC_SIZE = 16
AES_KEY_SIZE = 16
KPUB_SIZE = 64
KPRIV_SIZE = 32
ECIES_SIZE = 32
TO_CERT_SIZE = 136
TO_CERT_SUBJECT_CN_MAXSIZE = 64
SIGNATURE_SIZE = 64
KEY_FINGERPRINT_SIZE = 3
TIMESTAMP_SIZE = 4
TLS_RANDOM_SIZE = 32
TLS_MASTER_SECRET_SIZE = 48
TOCERTF_STANDALONE = 0
TOCERTF_SHORT = 1
TOCERTF_X509 = 2
TOCERTF_SHORT_V2 = 3
ECDH_PRE_MASTER_SECRET_SIZE = 16
ARC4_KEY_SIZE = 16
AES_KEY_SIZE = 16
HMAC_KEY_SIZE = 16
TO_MAXSIZE = 512

autocast = { 'str': str, 'hex': str, 'uint8': int, 'uint16': int }

CONF_DIR = '.TOsh'
